version: '3.4'
networks:
  thirdproject:
services:
  thirdproject-backend:
    image: phuongglsoft/thirdprojectbackend
    build:
        context: .
        dockerfile: ThirdProject-BackEnd\Dockerfile
    depends_on:
        - thirdproject-database
    networks:
        - thirdproject
    ports:
        - 8081:80
    environment:
        ASPNETCORE_URLS: http://+:80/
  thirdproject-database:
    container_name: postgresql
    image: postgres
    ports:
        - "5433:5432"
    environment:
        - "POSTGRES_PASSWORD=mysecretpassword"
    networks:
        - thirdproject 

        